
services:
  mongo:
    restart: always
    image: mongo:7.0.6
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - notify-network

  go-notify-local1:
    restart: always
    image: go-notify-local
    container_name: go-notify-local1
    command: sh -c "uvicorn main:app --reload --host 0.0.0.0 --port 8008"
    ports:
      - 8008:8008
    env_file:
      - ../../.env
    volumes:
      - ../../:/app
    networks:
      - notify-network
  
  go-notify-local2:
    restart: always
    image: go-notify-local
    container_name: go-notify-local2
    command: sh -c "uvicorn main:app --reload --host 0.0.0.0 --port 8008"
    ports:
      - 8007:8008
    env_file:
      - ../../.env
    volumes:
      - ../../:/app
    networks:
      - notify-network

  nginx:
    image: nginx:latest
    ports:
      - "8001:80" # Expose Nginx on port 80
    volumes:
      - ../../nginx.conf:/etc/nginx/nginx.conf:ro # Mount Nginx configuration
    depends_on:
      - go-notify-local1
      - go-notify-local2

networks: 
  notify-network:
    name: notify-network
    driver: bridge