services:
  go_notify:
    build: .
    container_name: go_notify_local
    command: sh -c "uvicorn main:app --reload --host 0.0.0.0 --port 8008"
    ports:
      - "8008:8008"
    env_file:
      - ../../.env
    volumes:
      - ../../:/app