version: '3.8'
services:
  # ... (app services)
  nginx:
    image: nginx:latest
    ports:
      - "8001:80" # Expose Nginx on port 80
    volumes:
      - ../../nginx.conf:/etc/nginx/nginx.conf:ro # Mount Nginx configuration

networks: 
  notify-network:
    name: notify-network
    driver: bridge